name: Validate JSON Formatting
on: [pull_request, workflow_dispatch]
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /Assets/OpenFlight-VRC/data_schema.json
          INPUT_JSONS: /Assets/OpenFlight-VRC/data.json
